<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Copyright>Developed by Orderli Software (orderli.com.au)</Copyright>
    <Company>Orderli Software</Company>
    <Product>SurfacePro Keyboard Client</Product>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>



