<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SurfaceTypeCoverManager.Services\SurfaceTypeCoverManager.Services.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <Copyright>Copyright © Orderli Software via Orderli Group 2026</Copyright>
    <Company>Orderli Software</Company>
    <Product>SurfacePro Keyboard Client</Product>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

